config/routes.rb
Rails.application.routes.draw do

  root to: 'borrowers#index'

  get 'home/borrower_index', to: 'home#borrower_index', as: 'index'

  resources :borrowers
 
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :invoices, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/borrower.rb
class Borrower < ApplicationRecord
    has_many :co_makers
    has_many :collaterals

    def interest
        monthly_pay * 0.20
    end



    def monthly_pay
        if nil
            self.price_lend / self.months_to_pay.to_i
        else
            self.price_lend / self.months_to_pay.to_i
        end
    end

    def weekly_pay
    end

end

app/models/co_maker.rb
class CoMaker < ApplicationRecord
    belongs_to :Borrower
end

app/models/collateral.rb
class Collateral < ApplicationRecord
    belongs_to :Borrower
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    has_many :invoice_items, dependent: :destroy

    STATUS_CLASS = {
        :draft => "badge badge-secondary",
        :sent => "badge badge-primary",
        :paid => "badge badge-success"
    }

    def subtotal
        self.invoice_items.map { |item| item.qty * item.price }.sum
    end

    def discount_calculated
        subtotal * (self.discount / 100.0)
    end

    def vat_calculated
        (subtotal - discount_calculated) * (self.vat / 100.0)
    end

    def total
        subtotal - discount_calculated + vat_calculated
    end

    def status_class
        STATUS_CLASS[self.status.to_sym]
    end
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:lend, :name, :surname, :email, :password, :password_confirmation, :remember_me])

    end 
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  def index
    redirect_to new_user_session_path unless user_signed_in?
    @borrower = scope
  end

  def show
    redirect_to new_user_session_path unless user_signed_in?
    @borrower = scope.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
          render pdf: "Invoice No. #{@borrower.id}",
          page_size: 'A4',
          template: "borrowers/show.html.erb",
          layout: "pdf.html",
          orientation: "Portrait",
          lowquality: true,
          zoom: 1,
          dpi: 75
      end
  end
  end

  def edit
  end

  def new
    @borrower = Borrower.new
  end

  def create
    @borrower = Borrower.new(borrower_params)

    if @borrower.save
      redirect_to index_path, notice: "Succesfully Fillup form wait to approve your application loan "
    end

  end

  private 

  def borrower_params
    params.require(:borrower).permit(:full_name,:address,:email,:loan_purpose,:price_lend,:phone_number,:months_to_pay)
  end

  def scope
    ::Borrower.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to new_user_session_path unless user_signed_in?
  end
  def borrower_index

  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = scope
    redirect_to new_user_session_path unless user_signed_in?
  end

  def show
    @invoice = scope.find(params[:id])

    respond_to do |format|
        format.html
        format.pdf do
            render pdf: "Invoice No. #{@invoice.id}",
            page_size: 'A4',
            template: "invoices/show.html.erb",
            layout: "pdf.html",
            orientation: "Landscape",
            lowquality: true,
            zoom: 1,
            dpi: 75
        end
    end
  end

private
    def scope
        ::Invoice.all.includes(:invoice_items)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/borrowers/Loanagreement.html.erb
<div class="newpage" id="page1" style="width: 902px; height: 1274px; transform: scale(1.10865); transform-origin: left top; display: block;">
<div class="text_layer" style="z-index:2"><div class="ie_fix">
&nbsp;
<div class="ff4" style="font-size:98px">
<span class="a" style="left:1794px;top:298px;word-spacing:3px">LOAN AGREEMENT </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:2069px;top:526px;word-spacing:-1px">I. Parties </span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:272px;top:739px">This </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:461px;top:739px">Loan Agreement </span></div>
<div class="ff1" style="font-size:85px">
<span class="a" style="left:1169px;top:738px">(“Agreement”)</span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:1778px;top:739px;word-spacing:-3px">entered into by and <span class="w7"></span>between: </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:545px;top:952px;word-spacing:29px">NAME OF BORROWER</span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:1514px;top:952px;word-spacing:28px">, of legal age, STATUS OF BORROWER, Filipino citizen and with </span><span class="a" style="left:272px;top:1059px;word-spacing:-3px">residence and postal address at <span class="w7"></span>ADDRESS OF BORROWER, </span></div>
<div class="ff3" style="font-size:77px">
<span class="a" style="left:2555px;top:1058px;word-spacing:-3px">hereafter called the “</span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:3365px;top:1059px">Borrower</span></div>
<div class="ff3" style="font-size:77px">
<span class="a" style="left:3774px;top:1058px">”,</span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:3827px;top:1059px">&nbsp;</span><span class="a" style="left:2182px;top:1272px;letter-spacing:-1px">and </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:545px;top:1485px;word-spacing:7px">NAME OF LENDER</span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:1305px;top:1485px;word-spacing:6px">, of legal age, STATUS OF LENDER, Filipino citizen and with residence and </span><span class="g" style="top:1591px"><span class="a" style="left:272px;word-spacing:-2px">postal address at ADDRESS OF LENDER, hereafter called the </span></span>
</div>
<div class="ff3" style="font-size:77px">
<span class="g" style="top:1591px"><span class="a" style="left:2621px">“</span></span>
</div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:2655px;top:1591px">Lender</span></div>
<div class="ff3" style="font-size:77px">
<span class="a" style="left:2953px;top:1591px">”.</span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:3005px;top:1591px">&nbsp;</span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:1991px;top:1805px;word-spacing:-2px">II. Effectivity </span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:272px;top:2018px;word-spacing:-2px">This Agreement is effective </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:1345px;top:2018px;word-spacing:-1px">EFFECTIVITY DATE.</span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:2170px;top:2018px">&nbsp;</span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:1883px;top:2232px;word-spacing:-1px">III. Period of Loan </span></div>
<div class="ff2" style="font-size:84px">
<span class="g" style="top:2444px"><span class="a" style="left:272px;word-spacing:-2px">This loan shall be <span class="w6"></span>payable for a period of&nbsp;</span></span>
</div>
<div class="ff4" style="font-size:84px">
<span class="g" style="top:2444px"><span class="a" style="left:1839px;word-spacing:-2px">&nbsp;____________</span></span>
</div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:2264px;top:2444px;word-spacing:-1px">, due on or before</span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:2945px;top:2444px;word-spacing:-3px">&nbsp;__________</span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:3302px;top:2444px">. </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:1910px;top:2658px;word-spacing:-1px">IV. Loan Amount </span></div>
<div class="ff2" style="font-size:84px">
<span class="g" style="top:2871px"><span class="a" style="left:272px">The </span></span>
</div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:440px;top:2871px">Borrower</span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:850px;top:2871px;word-spacing:-1px">&nbsp;promises to pay the Lender </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:1932px;top:2871px">&nbsp;AMOUNT OF LOAN </span><span class="a" style="left:2039px;top:3084px">V. Interest </span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:272px;top:3297px">The </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:448px;top:3297px">Borrower </span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:884px;top:3297px;word-spacing:6px">agrees to pay an interest with a fixed amount of AMOUNT OF INTEREST the interest </span><span class="a" style="left:272px;top:3404px;word-spacing:-2px">payment shall be payable on or before _____________ together with the Pri<span class="w6"></span>ncipal amount.</span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:3614px;top:3404px">&nbsp;</span><span class="a" style="left:1655px;top:3724px">VII. Method of Loan Payment </span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:272px;top:3937px">The </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:457px;top:3937px">Borrower </span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:902px;top:3937px;word-spacing:14px">shall make all payments called for under this loan agreement by CASH personally </span><span class="a" style="left:272px;top:4044px;word-spacing:-2px">served to the </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:798px;top:4044px">Lender</span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:1095px;top:4044px">. </span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:1751px;top:4364px;word-spacing:-1px">VIII. Non-waiver of right </span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:272px;top:4576px;word-spacing:11px">The failure of either Party to enforce any provision of this</span></div>
<div class="ff4" style="font-size:84px">
<span class="a" style="left:2623px;top:4576px;word-spacing:13px">&nbsp;Agreement&nbsp;</span></div>
<div class="ff2" style="font-size:84px">
<span class="a" style="left:3117px;top:4576px;word-spacing:11px">&nbsp;shall not be construed as a </span><span class="a" style="left:272px;top:4683px;word-spacing:8px">waiver or limitation of any parties right to subsequently enforce and compel strict compliance with </span><span class="a" style="left:272px;top:4789px;word-spacing:-2px">every provision of this <span class="w6"></span>Agreement. </span></div>
</div>
</div>
<div class="image_layer" style="z-index: 1">
<div class="ie_fix">
<img class="absimg" style="left: 562px; top: 671px; width: 189px; height: 3px; clip: rect(1px, 188px, 2px, 1px); display: block;" src="https://html.scribdassets.com/qg32opikg78y549/images/1-3dc72075b2.jpg">
</div>
</div>
</div>

app/views/borrowers/_contract.html.erb
<div style="background-color:;padding:20px;margin-top:50px;">
<div style="text-align:center">
    <p style="te"><h4>Loan Agreement</h4><p><br>
    <b>I. Parties</b>
<div>
<p>this Loan Agreement ("Agreement") entered into by and between: </p><br>
<p><%= @borrower.full_name.upcase%> , of legal age, STATUS OF BORROWER, Filipino citizen and with residence and postal address at <%= @borrower.address.upcase%>b, 

hereafter called the 
Borrower </p>

and <br>

<p>NAME OF LENDER , of legal age, STATUS OF LENDER, Filipino citizen and with residence and postal address at ADDRESS OF LENDER, hereafter called the Lender</p>
<br>
<div style="text-align:center">
    <b><p>II. Effectivity</p></b>
<div>

<p>This Agreement is effective EFFECTIVITY DATE.</p> <br>

<div style="text-align:center">
    <b><p>III. Period of Loan</p></b> 
<div>

<p>This loan shall be payable for a period of____________due on or before __________ </p><br>

<div style="text-align:center">
    <b><p>IV. Loan Amount The</p></b> 
<div>
<p>The Borrower promises to pay the Lender AMOUNT OF LOAN </p><br> 

<div style="text-align:center">
    <b><p>V. Interest</p></b> 
<div>

<p>agrees to pay an interest with a fixed amount of AMOUNT OF INTEREST the interest payment shall be payable on or before _____________ together with the Principal amount.</p> <br>

<div style="text-align:center">
    <b><p>VI. Method of Loan Payment </p></b> 
<div>
<p>The Borrower shall make all payments called for under this loan agreement by CASH personally  served to the lender</p> <br>

<div style="text-align:center">
    <b><p>VII. Non-waiver of right</p></b> 
<div>
<p>The failure of either Party to enforce any provision of this
shall not be construed as a 
waiver or limitation of any parties right to subsequently enforce and compel strict compliance with 
 provision of this Agreement. </p> <br>
        <div class="left-sign">
            <!-- Space for signature. -->
            <br/>
            <br/>
            <br/>
            <b><%= @borrower.full_name.upcase%></b><br/>
            <hr>
            Signature over printed name<br/>
        </div>
        <div class="rigth-date">
            <!-- Space for signature. -->
            <br/>
            <br/>
            <br/>
            <b></b><br/>
            <hr>
            Date / D / M / Y <br/>
        </div>
    </div>
</div>

app/views/borrowers/create.html.erb
%h1 Borrowers#create
%p Find me in app/views/borrowers/create.html.haml

app/views/borrowers/edit.html.erb
%h1 Borrowers#edit
%p Find me in app/views/borrowers/edit.html.haml

app/views/borrowers/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">full_name</th>
      <th scope="col">address</th>
      <th scope="col">phone_number</th>
      <th scope="col">email</th>
      <th scope="col">loan_purpose</th>
      <th scope="col">price_lend</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @borrower.each do |invoice| %>
      <tr>
        <th scope="row"><%= invoice.created_at.strftime('%d/%m/%Y') %></th>
        <td><%= invoice.full_name %></td>
        <td><%= invoice.address %></td>
        <td><%= invoice.phone_number %></td>
        <td><%= invoice.email %></td>
        <td><%= invoice.loan_purpose %></td>
        <td><%= invoice.price_lend %></td>
        <td><%= link_to 'View', borrower_path(invoice.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/borrowers/new.html.erb
<div class="wrapperborrower">
<div id="formContentborrower">
<h2>Personal Info</h2>
<hr>
<%= form_with(model: @borrower, local: true) do |f| %>
  <div class="form-row">
    <div class="form-group col-md-5">
      <%= f.label :Fullname %>
      <%= f.text_field :full_name, class:'form-control', placeholder: "Juan dela Cruz"%>
    </div>
    <div class="form-group col-md-5">
      <%= f.label :email %><br />
      <%= f.text_field :email, autofocus: true, autocomplete: "email",class: "form-control", placeholder: "juan123@gmail.com" %>
    </div>
  </div>
  <div class="form-row">
  <div class="form-group col-md-9">
    <%= f.label :Address %><br />
    <%= f.text_field :address, class: "form-control", placeholder:"1234 Main St" , rows:"3" %>
  </div>
  <div class="form-group col-md-3">
    <%= f.label :phone_number %>
    <%= f.number_field :phone_number, class:"form-control", placeholder: "+09269974562" %>
  </div>
  </div>
  <hr>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :loan_purpose %>
      <%= f.select :loan_purpose, ['Housing Loan' , 'School Loan' , 'Gudget Loan' , 'Personal Loan','Utility Bills Loan' , 'Others'],  {include_blank: false}, class: "form-control input-sm selectpicker"%>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :price_lend %><br />
      <%= f.number_field :price_lend, class: "form-control" %>
    </div>
    <div class="form-group col-md-2">
      <%= f.label :month_to_pay %><br />
      <%= f.select :months_to_pay, ['3', '4', '5', '6' , '12'],  {include_blank: false} , class: "form-control" %>
    </div>
  </div>
 
  <div class="actions">
    <%= f.submit "Submit",class:"btn btn-primary" %>
  </div>
<% end %>
</div>
</div>

app/views/home/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">DATE</th>
      <th scope="col">TOTAL DUE</th>
      <th scope="col">INTEREST DUE</th>
      <th scope="col">PRINCIPAL DUE</th>
      <th scope="col">SHOULD-BE BALANCE</th>
      <th scope="col">STATUS</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td>
        </td>
        <td>
        </td>
        <td>
        </td>
        <td>
        </td>
        <td>
          <%= number_with_delimiter(current_user.lend, :delimiter => ',')%>
          
        </td>
        <td></td>
      </tr>
      <tr>
        <%# <th scope="row"><%= invoice.created_at.strftime('%d/%m/%Y') %></th> 
        <td><%= current_user.created_at + 1.month %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6
            int = mon * 0.20 + mon
            number_with_delimiter(int, :delimiter => ',')
        %></td>
          <td><%= 
           num =  current_user.lend 
            ini = num / 6 
            int = ini * 0.20
            int.ceil(2)
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6.00 
            bal = current_user.lend - mon 
            bal.ceil(2)
        %></td>
        <td>
           <%# Status: <span class="<%= @invoice.status_class %>    
           <%# "> <%= @invoice.status</span> %>
        </td>
      </tr>
      <tr>
       <td><%= current_user.created_at + 2.month %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6
            int = mon * 0.20 + mon
        %></td>
          <td><%= 
           num =  current_user.lend 
            ini = num / 6 
            int = ini * 0.20
            int.ceil(2)
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6.00 * 2
            bal = current_user.lend - mon 
            bal.ceil(2)
        %></td>
        <td></td>
      </tr>
       <tr>
       <td><%= current_user.created_at + 3.month %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6
            int = mon * 0.20 + mon
        %></td>
          <td><%= 
           num =  current_user.lend 
            ini = num / 6 
            int = ini * 0.20
            int.ceil(2)
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6.00 * 3
            bal = current_user.lend - mon
            bal.ceil(2) 
        %></td>
        <td></td>
      </tr>
       <tr>
       <td><%= current_user.created_at + 4.month %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6
            int = mon * 0.20 + mon
        %></td>
          <td><%= 
           num =  current_user.lend 
            ini = num / 6 
            int = ini * 0.20
            int.ceil(2)
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6.00 * 4
            bal = current_user.lend - mon 
            bal.ceil(2)
        %></td>
        <td></td>
      </tr>
       <tr>
       <td><%= current_user.created_at + 5.month %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6
            int = mon * 0.20 + mon
        %></td>
          <td><%= 
           num =  current_user.lend 
            ini = num / 6 
            int = ini * 0.20
            int.ceil(2)
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6.00 * 5
            bal = current_user.lend - mon 
            bal.ceil(2)
        %></td>
        <td></td>
      </tr>
       <tr>
       <td><%= current_user.created_at + 6.month %></td>
        <td style="border-bottom-color: #92a8d1; border-bottom-style: solid;"><%= 
           num =  current_user.lend 
            mon = num / 6
            int = mon * 0.20 + mon
        %></td>
          <td style="border-bottom-color: #92a8d1; border-bottom-style: solid;"><%= 
           num =  current_user.lend 
            ini = num / 6 
            int = ini * 0.20
            int.ceil(2)
        %></td>
        <td style="border-bottom-color: #92a8d1; border-bottom-style: solid;"><%= 
           num =  current_user.lend 
            mon = num / 6
        %></td>
        <td><%= 
           num =  current_user.lend 
            mon = num / 6.00 * 6
            bal = current_user.lend - mon 
            bal.ceil(2)
        %></td>
      <td></td>
      </tr>
       <tr>
        <td>
        </td>
        <td>
           <%= 
           num =  current_user.lend 
            mon = num / 6
            int = mon * 0.20 + mon

            total = int * 6
            number_with_delimiter(total, :delimiter => ',')
        %>
        </td>
        <td>
          <%=
            num =  current_user.lend 
            ini = num / 6 
            int = ini * 0.20
            total = int * 6
            total.ceil(2)
            number_with_delimiter(total.ceil(2), :delimiter => ',')
          %>
        </td>
        <td>
         <%=
          num =  current_user.lend 
          mon = num / 6.00
          total = mon * 6

          number_with_delimiter(total, :delimiter => ',')
         %>
        </td>
        <td>
        </td>
        <td></td>
      </tr>
  </tbody>
</table>

app/views/invoices/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col">Status</th>
      <th scope="col">Discount (%)</th>
      <th scope="col">VAT (%)</th>
      <th scope="col">TOTAL</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <th scope="row"><%= invoice.created_at.strftime('%d/%m/%Y') %></th>
        <td><%= invoice.from_full_name %></td>
        <td><%= invoice.to_full_name %></td>
        <td><span class="<%= invoice.status_class %>"><%= invoice.status %></span></td>
        <td><%= invoice.discount %></td>
        <td><%= invoice.vat %></td>
        <td><%= number_to_currency(invoice.total) %></td>
        <td><%= link_to 'View', invoice_path(invoice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>PDFs | Ruby on Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/shared/header" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>

  </body>
</html>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
   <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%# <i class="far fa-user"></i> %>
        <span class="m-l-2">
        <%if user_signed_in? %>
          <%= current_user.name%> <%=  current_user.surname %></span>
           <div class="nav-item mx-0 mx-lg-1"> <%= image_tag wicked_pdf_asset_base64('logo9_7_164127.png'), :size => '150x50',class:"logo" %></div>
          <%else%>
           <div class="nav-item mx-0 mx-lg-1"> <%= image_tag wicked_pdf_asset_base64('logo9_7_164127.png'), :size => '150x50',class:"logo" %></div>
          <% end %>
        <% end %>
    </ul>
      <% if action_name.to_sym == :show %>
        <%= link_to 'Back', root_path, class: "btn btn-outline-secondary mx-2" %>
        <%= link_to 'DOWNLOAD PDF', borrower_path(::Borrower.find(params[:id]), format: :pdf), class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
      <%- if user_signed_in? %>
        <%= link_to destroy_user_session_path ,class: "btn btn-outline-secondary mx-2", method: :get do %>
          log out <i class="fas fa-sign-out-alt"></i>              
        <% end %>
        <% else %>
          <%= link_to new_borrower_path,class: "btn btn-outline-secondary mx-2" , method: :delete do %>
            Loan Form <i class="fas fa-newspaper"></i>
          <%end%>
          <%= link_to new_user_session_path,class: "btn btn-outline-secondary mx-2", method: :delete do %>
            Sign IN  <i class="fas fa-sign-out-alt"></i>
          <%end%>
      <% end%>
    </div>
  </div>
</nav>